# Generated by Django 3.2.6 on 2021-08-28 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Departement',
            fields=[
                ('DepartementId', models.AutoField(primary_key=True, serialize=False)),
                ('DepartementName', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('EmployeeId', models.AutoField(primary_key=True, serialize=False)),
                ('EmployeeName', models.CharField(max_length=200)),
                ('Departement', models.CharField(max_length=500)),
                ('DateOfJoining', models.DateTimeField()),
                ('PhotoFileName', models.CharField(max_length=500)),
            ],
        ),
    ]
